server:
  port: 80
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/sistema?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456789
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    initialSize: 1
    minIdle: 2
    maxActive: 5
    maxIdle: 5
  jpa:
    hibernate:
      hbm2ddl:
        auto: none
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
